# Generated by Django 6.0.1 on 2026-01-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominado',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
